### ISSUE TITLE
getting blank screen after installation of the package

### ISSUE THREAD

**Issue by ramsaiphp** [pipe-dream/laravel#44]
Ops! To get faster help you might want to supply the following:

* A clear and concise description of what the bug is.
* Steps to reproduce the behavior
* OS, browser
* pipe-dream version

Thank you!

**Comment by ramsaiphp** [comment]
Hi,

After installing the package in my existing laravel repo with composer i went to browser and checked http://mysite/pipe-dream giving blank white screen

I am using Laragon in windows 10. Are there any restrictions for this?
Please let me know
Thanks
Ramsai

**Comment by septIO** [comment]
@ramsaiphp Did you run `npm install`? Might also have to build the files with `npm run dev`

**Comment by ramsaiphp** [comment]
you just asked to run composer i did that only. You didnt mention npm in installation part.

**Comment by septIO** [comment]
@ramsaiphp Did it work after running those two commands? I use Laragon aswell, and have no issues on my end.

**Comment by septIO** [comment]
This bug was introduced in #43

**Comment by ramsaiphp** [comment]
No still getting blank screen only

**Comment by a-di-ez** [comment]
I have too

**Comment by septIO** [comment]
@ramsaiphp and @a-di-ez This can temporarily be fixed by downgrading to version `^0.0.65`

**Comment by ramsaiphp** [comment]
Yes when i revert back to 0.0.65 it is loading fine thanks@septIO

**Comment by mateusjunges** [comment]
I have tested #42 and think that @ajthinking also did it. It's working for me.
Kali Linux, laravel 5.8.

**Comment by septIO** [comment]
@mateusjunges When i upgrade form 0.0.65 to 0.0.66 i get this error in the console:
`Error: Cannot find module '@objectModel/SketchParser'`

Stack trace:
```
Error: Cannot find module '@objectModel/SketchParser' app.js:210088:45
    webpackMissingModule http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:210088
    js http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:210088
    __webpack_require__ http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:20
    js http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:207745
    __webpack_require__ http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:20
    0 http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:211100
    __webpack_require__ http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:20
    <anonymous> http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:84
    <anonymous> http://nordic-api.test/vendor/pipe-dream/laravel/js/app.js:87
```

**Comment by mateusjunges** [comment]
Ok, trying to reproduce it right now... just a moment

**Comment by ajthinking** [comment]
Check this out: https://github.com/pipe-dream/laravel/releases/tag/v0.067 does it fix it?

**Comment by septIO** [comment]
@ajthinking 0.067 works again
New issue though: 
![image](https://user-images.githubusercontent.com/8553590/60097673-21b3f680-9754-11e9-82d0-63b4eb6ebc23.png)

APIResourcePipe is shown and bound twice

**Comment by mateusjunges** [comment]
Working for me.
![Screenshot from 2019-06-25 09-15-36](https://user-images.githubusercontent.com/19756164/60097471-d84eb180-9729-11e9-9927-b5d3272a5dfe.png)

**Comment by mateusjunges** [comment]
@septIO i think it's related to #39. The same is happening here.

**Comment by ajthinking** [comment]
Just pushed fix

**Comment by ajthinking** [comment]
https://github.com/pipe-dream/laravel/releases/tag/v0.068

**Comment by ajthinking** [comment]
Its kind of hard to PR to this repo because no tests... :) Thanks everybody for debug

**Comment by septIO** [comment]
@ajthinking Might want to fix your versioning.
We had: 
0.0.6 ->0.0.65
-> 0.0.66
-> 0.067 <- notice the missing dot
-> 0.068

**Comment by ajthinking** [comment]
Thanks @septIO here is the latest fixes in correct numbering: https://github.com/pipe-dream/laravel/releases/tag/v0.0.69

I wish there was some feature to release incrementally with just +1 at the end haha
